package pt.tecnico.distledger.server.domain.operation;

import pt.ulisboa.tecnico.distledger.contract.DistLedgerCommonDefinitions;
import pt.ulisboa.tecnico.distledger.contract.DistLedgerCommonDefinitions.OperationType;

public class TransferOp extends Operation {
    private String destAccount;
    private int amount;

    public TransferOp(String fromAccount, String destAccount, int amount) {
        super(fromAccount);
        this.destAccount = destAccount;
        this.amount = amount;
    }

    public String getDestAccount() {
        return destAccount;
    }

    public void setDestAccount(String destAccount) {
        this.destAccount = destAccount;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    // Converts TransferOp to Operation class generated by protobuf
    @Override
    public DistLedgerCommonDefinitions.Operation toGRPC() {
        DistLedgerCommonDefinitions.Operation.Builder operBuilder;
        operBuilder = DistLedgerCommonDefinitions.Operation.newBuilder();
        OperationType type = OperationType.OP_TRANSFER_TO;
        operBuilder.setAmount(this.getAmount());
        operBuilder.setDestUserId(this.getDestAccount());
        operBuilder.setType(type);
        operBuilder.setUserId(this.getAccount());
        DistLedgerCommonDefinitions.Operation operation = operBuilder.build();
        return operation;
    }
}
