package pt.tecnico.distledger.server.domain.operation;

import pt.ulisboa.tecnico.distledger.contract.DistLedgerCommonDefinitions;
import pt.ulisboa.tecnico.distledger.contract.DistLedgerCommonDefinitions.OperationType;

public class DeleteOp extends Operation {

    public DeleteOp(String account) {
        super(account);
    }

    // Converts DeleteOp to Operation class generated by protobuf
    @Override
    public DistLedgerCommonDefinitions.Operation toGRPC() {
        DistLedgerCommonDefinitions.Operation.Builder operBuilder;
        operBuilder = DistLedgerCommonDefinitions.Operation.newBuilder();
        OperationType type = OperationType.OP_DELETE_ACCOUNT;
        operBuilder.setType(type);
        operBuilder.setUserId(this.getAccount());
        DistLedgerCommonDefinitions.Operation operation = operBuilder.build();
        return operation;
    }

}
