package pt.tecnico.distledger.server.domain.operation;

import pt.ulisboa.tecnico.distledger.contract.DistLedgerCommonDefinitions;
import pt.ulisboa.tecnico.distledger.contract.DistLedgerCommonDefinitions.OperationType;

public class CreateOp extends Operation {

    public CreateOp(String account) {
        super(account);
    }

    // Converts CreateOp to Operation class generated by protobuf
    @Override
    public DistLedgerCommonDefinitions.Operation toGRPC() {
        DistLedgerCommonDefinitions.Operation.Builder operBuilder;
        operBuilder = DistLedgerCommonDefinitions.Operation.newBuilder();
        OperationType type = OperationType.OP_CREATE_ACCOUNT;
        operBuilder.setType(type);
        operBuilder.setUserId(this.getAccount());
        operBuilder.addAllPrevTS(this.getPrevTS());
        operBuilder.addAllTS(this.getReplicaTS());
        operBuilder.setStable(this.isStable());
        DistLedgerCommonDefinitions.Operation operation = operBuilder.build();
        return operation;
    }

}
